# Базовые параметры настройки конфигурации проекта
dbname: etal # В классе менять не надо
user: postgres # Замените на свой логин от БД в классе
password: Q1w2e3r4 # Замените на свой пароль от БД в классе
host: 127.0.0.1 # Замените на 192.168.0.48 в классе
dbtableprefix: ""  # Замените на свой логин от БД